learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('', views.index, name='index'),
    path('registration', views.registration, name='registration'),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views as basic_app_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('', basic_app_views.index, name='index')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserInfo(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserInfo

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse('You are logged in, Nice!')


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('account not active')
        else:
            print("someone failed login")
            print("username: {} and Password: {}".format(username, password))
            return HttpResponse('invalid login details supplied')
    else:
        return render(request, 'basic_app/login.html', {})

def registration(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserInfo(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserInfo()
    return render(request, 'basic_app/registration.html', context={'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

learning_users/templates/basic_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <title>
      {% block title_block %}
      {% endblock %}
    </title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-ligth">
      <div class="container">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:index' %}">Home</a>
          </li>
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'basic_app:logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" href="{% url 'basic_app:login' %}">Login</a>
            {% endif %}
          </li>
            <a class="nav-link" href="{% url 'basic_app:registration' %}">Register</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>
    <script src="{% static "js/jquery-3.3.1.min.js" %}"></script>
    <script src="{% static "js/tether.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block title_block %}
Index
{% endblock %}
{% block body_block %}
<h1>Home</h1>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}
<div class="jumbotron">
  <h1>Please login</h1>
  <form action="{% url 'basic_app:login' %}" method="post">
    {% csrf_token %}
    <div class="row justify-content-center">
      <div class="col-12">
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" class="form-control" name="username" placeholder="Enter username">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" name="password" class="form-control">
        </div>
        <input type="submit" class="btn btn-primary" value="login">
      </div>
    </div>

  </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% block title_block %}
Register
{% endblock %}
{% block body_block %}
<h1>Register</h1>
{% if registered %}
<h1>Thank you for registering!</h1>
{% else %}
<h1>Register here</h1>
<h3>Fill out the form</h3>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ user_form.as_p }}
  {{ profile_form.as_p }}
  <input type="submit" value="Register" class="btn btn-primary">
</form>
{% endif %}
{% endblock %}